version: 2
jobs:
  build:
    docker:
      - image: circleci/golang:1.14
    steps:
      - checkout

      - run: go build
      - run: go test -v -cover -coverprofile=coverage.txt ./...
      - run: bash <(curl -s https://codecov.io/bash)